import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Moveable from "react-moveable";
import InfiniteViewer from "react-infinite-viewer";
import * as React from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const viewerRef = React.useRef<InfiniteViewer>(null);

  React.useEffect(() => {
      setTimeout(() => {
          viewerRef.current!.scrollCenter();
      }, 100);
  }, []);

  const scrollOptions = {
      container: () => viewerRef.current!.getContainer(),
      threshold: 20,
      getScrollPosition: () => {
          return [
              viewerRef.current!.getScrollLeft({ absolute: true }),
              viewerRef.current!.getScrollTop({ absolute: true }),
          ];
      },
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <InfiniteViewer className="infinite-viewer" ref={viewerRef}>
            <div className="viewport">
                <div className="target">Target</div>
                <Moveable
                    scrollable={true}
                    scrollOptions={scrollOptions}
                    target={".target"}
                    draggable={true}
                    resizable={true}
                    rotatable={true}
                    onRender={e => {
                        e.target.style.cssText += e.cssText;
                    }}
                    onScroll={({ direction }) => {
                        viewerRef.current!.scrollBy(direction[0] * 10, direction[1] * 10);
                    }}
                ></Moveable>
            </div>
        </InfiniteViewer>
      {/* <main className={`${styles.main} ${inter.className}`}>
      </main> */}
    </>
  )
}
